### ISSUE TITLE
Viewing Temporal Gear 

### ISSUE THREAD

**Issue by TheZenNinja** [SpearAndFang/translocator-engineering-redux#1]
I did not do in depth testing so it might be a conflict between this mod and another, but I wanted to bring this to your attention since the crash originates from your mod in the crash report.

`System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at TranslocatorEngineering.ModSystem.ItemLinker.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)`

```
Running on 64 bit Windows with 48 GB RAM 
Game Version: v1.17.11 (Stable)
2/28/2023 1:22:38 PM: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.11, weaponpacka@1.3.1, ancienttools@1.4.9, backpackpackplus@1.0.3, betterruins@0.0.7, BuggisRandomChanges@3.1.0, cavecontent@1.0.1, cralutweaks@1.0.2, harptech@0.2.3, instruments@1.1.5, meteoricexpansion@1.2.2, morestickcrafts@1.17.9-1.0, qptech@1.11.0, survivalcats@1.2.3-rc.2, locustmod@2.3.6, translocatorengineeringredux@1.4.0, usefuldrifterloot@1.0.2, game@1.17.11, egocaribautomapmarkers@2.4.0-pre.1, Bettermedievalexpansion@3.8.0, carryon@0.9.0, claywheel@1.0.0, cosmosis@0.5.0, deathwaypoints@1.0.3, electricity@0.0.7, expandedfoods@1.6.5, medievalexpansion@3.8.1, moreicons@1.0.3, morepiles@1.2.2, mcrate@1.0.4, petai@1.5.5, prospectorinfo@4.1.2, smeltableingots@1.0.0, stonequarry@2.0.0-rc.4, tpnet@1.8.0-rc.1, th3dungeon@0.1.1, creative@1.17.11, survival@1.17.11, xrowboat@0.0.5, metalrecovery@0.1.18-rc.2, depositstretcher@0.1.1, feverstonehorses@1.4.1, onestick@1.0.1, treetapping@1.0.0, wolftaming@1.5.4, xinvtweaks@1.4.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at TranslocatorEngineering.ModSystem.ItemLinker.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 389
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 197
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 285
   at Vintagestory.API.Client.SlideshowItemstackTextComponent.RenderInteractiveElements(Single deltaTime, Double renderX, Double renderY, Double renderZ) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\SlideshowItemstackTextComponent.cs:line 200
   at Vintagestory.API.Client.GuiElementRichtext.RenderInteractiveElements(Single deltaTime) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 486
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 711
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 373
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 303
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1350
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 720
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 624
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 131
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2/26/2023 7:13:12 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2186699272363415476, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\USER\AppData\Local\Temp\RDR4B81.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B91.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B92.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4B8F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4BDE.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 9de9bffb-8114-4ace-b4d1-2938e216dd26
Report Status: 268435456
Hashed bucket: 0215b19e9f6a6c1d1e58b7670fd397b4
Cab Guid: 0 }
--------------
{ TimeGenerated = 11/23/2022 9:10:02 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2177858694758095880, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.0.0
P3: 10.0.19044.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\USER\AppData\Local\Temp\RDRCD82.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD83.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDC3.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDC2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCE01.tmp.txt

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: b8757a21-26d7-4240-8eef-bc634012223e
Report Status: 268435456
Hashed bucket: cd7dc5185a521ef09e394ef1b00d5c08
Cab Guid: 0 }
```

[client-crash.txt](https://github.com/SpearAndFang/translocator-engineering-redux/files/10853705/client-crash.txt)

**Comment by TheZenNinja** [comment]
Im stupid and was using mod version 1.4.0 on VS 1.17. It works as intended with mod version 1.3.0

**Comment by SpearAndFang** [comment]
[TheZenNinja](https://github.com/TheZenNinja)

Nailed it.
